
networks:
  default: hardhat-fork
  mainnet-fork:
    cmd_settings:
      evm_version: london

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - smartcontractkit/chainlink@1.6.0

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.10
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      - "@chainlink=smartcontractkit/chainlink@1.6.0"

reports:
  exclude_contracts:
    - SafeMath
