[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'forge_tests'
cache_path  = 'forge-cache'

[fuzz]
runs = 1000
max_test_rejects = 655360
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
