on:
  push:
    branches:
      - main
  pull_request:

name: Smart Contract Unit tests

env:
  ETHERSCAN_TOKEN: EIR8RN3REQHWQ8UW11Z9NBVMVA3H7GE56Z
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: 4f67c945bb4549e8948eb241e2f86ba3
  WEB3_ALCHEMY_PROJECT_ID: Q5dMZcBXQgzhVeNixaf0cnKlZEDXbd7x

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Compiler Installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install hardhat & dependencies
      run: npm install

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Set correct provider
      run: brownie networks modify mainnet host=https://eth-mainnet.alchemyapi.io/v2/\$WEB3_ALCHEMY_PROJECT_ID

    - name: Run Tests
      run: brownie test --network hardhat-fork
